require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"

  task :console do
    Pry.start
  end

# task :something do 
#   puts "IDK what I want to do here"
# end
